name: NODE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          npm ci
          npm run build
        working-directory: src/nodejs

      - name: save build artifacts for later step
        if: contains(github.ref, '/master')
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: src/nodejs/dist
          if-no-files-found: error
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          npm ci
          npm run test
        working-directory: src/nodejs

  
  get_version:
    runs-on: ubuntu-latest
    if: contains(github.ref, '/master')
    outputs:
      version: ${{ steps.final-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: get-package-version
        id: package-version
        uses: stevenbenitez/get-package-version-action@v1
        with:
          path: src/nodejs

      - name: get latest published version
        id: published-version
        uses: Bruce17/ghaction-package-latest-version@v1.1.2
        with:
          package: hallpass
          language: node

      - name: print versions
        run: |
          echo "Package: ${{ steps.package-version.outputs.version }}"
          echo "NPM: ${{ steps.published-version.outputs.latestVersion }}"

      - name: bump version
        id: bump-version
        if: ${{ steps.package-version.outputs.version == steps.published-version.outputs.latestVersion }}
        uses: olegsu/semver-action@v1
        with:
          version: ${{ steps.package-version.outputs.version }}

      - name: update version in package.json
        id: update-version
        if: ${{ steps.package-version.outputs.version == steps.published-version.outputs.latestVersion }}
        uses: HarmvZ/set-package-json-version-action@v0.1.2
        with:
          version: ${{ steps.bump-version.outputs.version }}
          path: src/nodejs

      - name: update git with updated version
        if: ${{ steps.package-version.outputs.version == steps.published-version.outputs.latestVersion }}
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: get-final-version
        id: final-version
        uses: stevenbenitez/get-package-version-action@v1
        with:
          path: src/nodejs


  publish:
    runs-on: ubuntu-latest
    needs: [build, test, get_version]
    if: contains(github.ref, '/master')
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "version: ${{ needs.get_version.outputs.version }}"

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: copy files into package folder
        run: |
          mkdir package
          cp src/nodejs/package.json ./package
          cp src/nodejs/README.md ./package
          cp LICENSE ./package
          cp dist ./package -r

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: publish to NPM
        run: npm publish
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}