name: NODE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          npm ci
          npm run build
        working-directory: src/nodejs

      - name: save build artifacts for later step
        if: contains(github.ref, '/master')
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: src/nodejs/dist
          if-no-files-found: error
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  
  get_version:
    runs-on: ubuntu-latest
    if: contains(github.ref, '/master')
    steps:
      - uses: actions/checkout@v3


  publish:
    runs-on: ubuntu-latest
    needs: [build, test, get_version]
    if: contains(github.ref, '/master')
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: dist

      - name: copy files into package folder
        run: |
          mkdir package
          cp src/nodejs/package.json ./package
          cp src/nodejs/README.md ./package
          cp LICENSE ./package
          cp dist ./package -r